In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("StudentsPerformance.csv")
df

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [3]:
df.keys()

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [4]:
df.head(2)

gender race/ethnicity parental level of education     lunch  \
0  female        group B           bachelor's degree  standard   
1  female        group C                some college  standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88

In [6]:
df["gender"].unique()

array(['female', 'male'], dtype=object)

In [7]:
df["race/ethnicity"].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [8]:
df["parental level of education"].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [9]:
from sklearn.preprocessing import LabelBinarizer, LabelEncoder, OneHotEncoder

In [11]:
LabelBinarizer().fit_transform(df["gender"])[:4]

array([[0],
       [0],
       [0],
       [1]])

In [12]:
LabelEncoder().fit_transform(df["gender"])[:4]

array([0, 0, 0, 1])

In [14]:
OneHotEncoder().fit_transform(df[["gender"]])[:4]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 2)>

In [16]:
array = OneHotEncoder().fit_transform(df[["race/ethnicity"]]).toarray()
array

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.]], shape=(1000, 5))

In [17]:
OneHotEncoder().fit_transform([["alb"], ["negru"], ["verde"]]).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
df.head(2)

gender race/ethnicity parental level of education     lunch  \
0  female        group B           bachelor's degree  standard   
1  female        group C                some college  standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88

In [19]:
df["gender"] = LabelBinarizer().fit_transform(df["gender"])
df

gender race/ethnicity parental level of education         lunch  \
0         0        group B           bachelor's degree      standard   
1         0        group C                some college      standard   
2         0        group B             master's degree      standard   
3         1        group A          associate's degree  free/reduced   
4         1        group C                some college      standard   
..      ...            ...                         ...           ...   
995       0        group E             master's degree      standard   
996       1        group C                 high school  free/reduced   
997       0        group C                 high school  free/reduced   
998       0        group D                some college      standard   
999       0        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [21]:
df["race_label_encoded"] = LabelEncoder().fit_transform(df["race/ethnicity"])
df

gender  race/ethnicity parental level of education         lunch  \
0         0               1           bachelor's degree      standard   
1         0               2                some college      standard   
2         0               1             master's degree      standard   
3         1               0          associate's degree  free/reduced   
4         1               2                some college      standard   
..      ...             ...                         ...           ...   
995       0               4             master's degree      standard   
996       1               2                 high school  free/reduced   
997       0               2                 high school  free/reduced   
998       0               3                some college      standard   
999       0               3                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     race_label_encoded  
0                     1  
1                     2  
2                     1  
3                     0  
4                     2  
..                  ...  
995                   4  
996                   2  
997                   2  
998                   3  
999                   3  

[1000 rows x 9 columns]

In [23]:
race_sparse_data = OneHotEncoder().fit_transform(df[["race/ethnicity"]])

In [ ]:
groups_array = df[""]

In [ ]:
dense_df = pd.DataFrame(race_sparse_data.toarray(), columns=df["race/ethnicity"].unique().sort())
dense_df