numpy = numerical python

In [2]:
import numpy as np

array = o lista cu toate elementele de acelasi tip

In [3]:
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [4]:
arr = np.array([0, 1, 2, 3, 4])
type(arr), arr.dtype

(numpy.ndarray, dtype('int64'))

In [5]:
arr = np.array([0, 1, 2, 3.0, 4])
type(arr), arr.dtype

(numpy.ndarray, dtype('float64'))

In [6]:
arr = np.arange(10)
arr, type(arr), arr.dtype

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray, dtype('int64'))

In [7]:
arr = np.arange(10, 20)
arr, type(arr), arr.dtype

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 numpy.ndarray,
 dtype('int64'))

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones(10) * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [11]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [12]:
np.array([1, 2, 3]) ** 2

array([1, 4, 9])

In [13]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.arange(100) % 7

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1])

In [15]:
np.arange(100) % 7 == 0

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False])

In [16]:
np.arange(100) [np.arange(100) % 7 == 0]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [17]:
np.arange(100).reshape((10, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
np.arange(100).reshape((25, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [19]:
np.arange(100).reshape((4, 25))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
np.random.randint(1, 100, 3)

array([60, 87, 36], dtype=int32)

In [21]:
np.random.randint(1, 100, (3, 3))

array([[56, 86, 67],
       [93, 70, 41],
       [ 7, 27, 72]], dtype=int32)

In [22]:
np.random.random(3)

array([0.43592709, 0.14611966, 0.88060713])

In [23]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [26]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
array = np.random.randint(21, 23, 50)
array

array([21, 22, 21, 21, 22, 21, 21, 22, 22, 21, 22, 21, 21, 22, 22, 22, 21,
       22, 22, 22, 21, 21, 22, 21, 21, 21, 21, 22, 21, 21, 21, 21, 21, 22,
       22, 22, 21, 22, 21, 22, 22, 22, 21, 21, 22, 21, 21, 21, 21, 21],
      dtype=int32)

In [30]:
array[array == 22]

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22], dtype=int32)

In [31]:
array = np.random.randint(2, 100, 50)
array

array([16, 97,  8, 49, 48, 17, 52, 12, 24, 51, 83, 11, 57,  2, 60, 77, 62,
       42, 12,  5, 54, 61, 31, 85, 53, 70, 52, 88, 72, 90, 12, 43, 22, 58,
       15, 87,  5, 88, 53, 71, 78, 27, 42, 57, 79, 21, 39, 73,  5, 22],
      dtype=int32)

In [32]:
array.max()

np.int32(97)

In [33]:
array.max(), array.argmax()

(np.int32(97), np.int64(1))